version: "3.7"
services:
  family-organizer-server:
    build:
      context: ../family-organizer-server
    volumes:
      - ../family-organizer-server:/app
    working_dir: /app
    env_file:
      - ../.env
    restart: unless-stopped
    ports:
      - 5000:5000